packages:
  - docs
  - playground
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.10.1
  '@antfu/ni': ^24.2.0
  '@antfu/utils': ^9.1.0
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/vitepress-twoslash': ^3.2.1
  '@types/node': ^22.13.10
  '@unocss/reset': ^66.0.0
  '@vueuse/core': ^13.0.0
  bumpp: ^10.1.0
  eslint: ^9.22.0
  floating-vue: ^5.2.2
  lint-staged: ^15.5.0
  pinia: ^3.0.1
  simple-git-hooks: ^2.11.1
  tsup: ^8.4.0
  tsx: ^4.19.3
  typescript: ^5.8.2
  unocss: ^66.0.0
  unplugin-vue-components: ^28.4.1
  vite: ^6.2.2
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.4
  vitepress-plugin-group-icons: ^1.3.8
  vitest: ^3.0.9
  vue: ^3.5.13
